GCP:
  CLUSTER: myprojectcluster
  REGION: europe-west2
  SPARK_PATH_FILE: gs://your-bucket-name/code/transformation_spark.py
  DATA_BUCKET: your-bucket-name
  BIGQUERY_TABLE: de_project.report
GH:
  YEAR: 2023
  MONTH: 4
  DAY: 1
