GCP:
  CLUSTER: test
  REGION: europe-west-1
  SPARK_PATH_FILE: gs://de_project_bucket_de-zoomcamp-386310/code/transformation_spark.py
  TEMP_DATAPROC_BUCKET: 
  DATA_BUCKET: de_project_bucket_de-zoomcamp-386310
  BIGQUERY_TABLE: de_project.report
GH:
  YEAR: 2023
  MONTH: 1
  DAY: 16
  # Only accept True or False
