GCP:
  CLUSTER: test
  REGION: europe-west-1
  SPARK_PATH_FILE: prueba1
  TEMP_DATAPROC_BUCKET: prueba2
  DATA_BUCKET_PATH: gs://de_project_bucket_de-zoomcamp-386310/code/transformation_spark.py
  BIGQUERY_TABLE: de_project.report
GH:
  YEAR: 2023
  MONTH: 1
  DAY: 16
  # Only accept True or False
